### PR TITLE
Loading achievements from JSON files

### PR DESCRIPTION
**Pull request by Kesomannen**
Adds no-code functionality to the mod, inspired by the format for Minecraft advancements. Searches the plugin directory (and child directories) for directories named "Achievements" and tries to load all JSON files in there.

The format is as follows:
```json5
{
  "name": "Sprint",
  "display_text": "Press shift while moving",
  "description": "This is an easy one", // optional
  "icon": "icon.png", // optional, relative to the file's path, defaults to a similarly named .png file in the same directory
  "debug": false, // optional (defaults to false), logs every time the achievement would have been completed (even if it already is)
  "criteria": [
    {
      "trigger": "update", // snake_case name of the ITrigger type to use (update triggers every frame)
      "every": 10,
      "conditions": { // optional
        "player": { // property names in this map corresponds to ICondition types to use
            "sprinting": true
        }
      }
    }
  ]
}
```

Also adds a (public) Event namespace for events used by the triggers. Currently there's only one trigger and three conditions, so more will have to be added. No documentation yet either. It would be extremely nice to auto generate the docs from the XML comments with something like Doxygen.

### CODE REVIEW

**Comment by Kesomannen** [comment]
I added some more conditions. The triggers will be harder and require some patching. LC API has some nice events, but it's deprecated so we probably don't want it as a dependency. It is under the same license as this though, so we could just yank the code. Let me know what you think about that.

**Comment by MaxWasUnavailable** [comment]
> I added some more conditions. The triggers will be harder and require some patching. LC API has some nice events, but it's deprecated so we probably don't want it as a dependency. It is under the same license as this though, so we could just yank the code. Let me know what you think about that.

I've been considering a standalone event API for some other projects I work on, and have a basic version I've used internally while developing things. Might be interesting to further develop that as a nice, quality, standalone event API tbh. Let me know what you think regarding something like that - I'd be down to collaborate on it 😄

**Comment by Kesomannen** [comment]
I'm not sure, I think it's fine to make them in here for now,. I've already added some events for the player. Maybe I should change it to internal though (instead of public) so people don't depend on this mod for the events specifically. Especially if we might move to an external library for it.

**Comment by MaxWasUnavailable** [comment]
> I'm not sure, I think it's fine to make them in here for now,. I've already added some events for the player. Maybe I should change it to internal though (instead of public) so people don't depend on this mod for the events specifically. Especially if we might move to an external library for it.

That sounds good. I'll merge once that's done.

**Comment by Kesomannen** [comment]
pushed it

**Pull request merged**
